### ISSUE TITLE
unable to run LSTM model including  genertators

### ISSUE THREAD

**Issue by reyhanhgh** [rstudio/keras#1109]
I had an LSTM model that I had run many times without any issues. Due to some problems, I was obliged to re-install ubuntu on my machine and therefore to re-install R, R studio, keras and tensorFlow. Since, the re-installation of kears and TensorFlow, my script does not work any more. I was constantly asked to install cuda 10. I installed it following the instructions given by the [Rstudio AI blog ](https://tensorflow.rstudio.com/installation/gpu/local_gpu/), but it did not solve the problem.  I am getting this error :

```
2020-08-20 11:19:10.387062: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-20 11:19:10.422363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.422632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro K610M computeCapability: 3.5
coreClock: 0.954GHz coreCount: 1 deviceMemorySize: 980.00MiB deviceMemoryBandwidth: 19.37GiB/s
2020-08-20 11:19:10.422887: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 11:19:10.424243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-20 11:19:10.425486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-20 11:19:10.425776: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-20 11:19:10.427358: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-20 11:19:10.428161: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-20 11:19:10.431123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-20 11:19:10.431337: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.432140: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.432346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-20 11:19:10.432628: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-20 11:19:10.437910: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2793380000 Hz
2020-08-20 11:19:10.438228: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f6420000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-20 11:19:10.438243: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-20 11:19:10.470678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.471051: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5597adf6b180 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-20 11:19:10.471068: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro K610M, Compute Capability 3.5
2020-08-20 11:19:10.471272: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.471499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro K610M computeCapability: 3.5
coreClock: 0.954GHz coreCount: 1 deviceMemorySize: 980.00MiB deviceMemoryBandwidth: 19.37GiB/s
2020-08-20 11:19:10.471548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 11:19:10.471565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-20 11:19:10.471578: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-20 11:19:10.471592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-20 11:19:10.471606: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-20 11:19:10.471622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-20 11:19:10.471636: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-20 11:19:10.471709: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.471975: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.472174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-20 11:19:10.472209: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 11:19:10.473029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-20 11:19:10.473040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-20 11:19:10.473045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-08-20 11:19:10.473162: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.473432: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 11:19:10.473660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 70 MB memory) -> physical GPU (device: 0, name: Quadro K610M, pci bus id: 0000:01:00.0, compute capability: 3.5)
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
2020-08-20 11:19:10.486637: I tensorflow/stream_executor/cuda/cuda_driver.cc:763] failed to allocate 70.75M (74186752 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```
My LSTM model uses `fit_generator`. It does not however seem to be the problem since when I run the simple [MNIST example  ](https://blog.rstudio.com/2017/09/05/keras-for-r/), I get the same error and my Rstudio crashes. 

My Rstudio version : Version 1.3.1073

```
R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again     
```

```
> .rs.getPackageVersion("keras")
[1] ‘2.3.0.0.9000’
> .rs.getPackageVersion("tensorflow")
[1] ‘2.2.0.9000’
```
Your help would be very much appreciated.

**Comment by skeydan** [comment]
Maybe different OS processes are eating up GPU memory? It seems TF only gets 70M:

```
2020-08-20 11:19:10.473660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 70 MB memory) -> physical GPU (device: 0, name: Quadro K610M, pci bus id: 0000:01:00.0, compute capability: 3.5
```

You could check that using `nvidia-smi`.

**Comment by reyhanhgh** [comment]
@skeydan 
Hi Sigrid, yes, it is saying that but in fact there is no other processes running ... 

`Thu Aug 20 14:50:09 2020  `     
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K610M        On   | 00000000:01:00.0  On |                  N/A |
| N/A   52C    P0    N/A /  N/A |    731MiB /   980MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

What I am not understanding is that I had installed cuda 10 following the TensorFlow commands that I found on [Rstudio AI Blog](https://tensorflow.rstudio.com/installation/gpu/local_gpu/) . but in the configuration above it turns out to be cuda 11 ! could be due to this ?

**Comment by skeydan** [comment]
What CUDA installation commands exactly are you referring to? Are you sure you didn't obtain CUDA via the distribution? (Which should be totally fine on Ubuntu I think).

For me, CUDA 11 runs fine with TensorFlow 2.2 as well as 2.3.

For the above `nvidia-smi` output, as nearly all memory is taken but but no processes are found, perhaps there are zombies still holding on to it? Can you try restarting the machine, checking `nvidia-smi`, and then running the example code from https://tensorflow.rstudio.com/tutorials/beginners/?

Please also provide the output of `tensorflow::tf_config()`.

**Comment by reyhanhgh** [comment]
Thanks Sigrid for your follow-up. Regarding what you asked me in you comment :

- I executed all following installation commands

```
# Add NVIDIA package repositories
# Add HTTPS support for apt-key
sudo apt-get install gnupg-curl
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo apt-get update
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt install ./nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt-get update

# Install NVIDIA driver
# Issue with driver install requires creating /usr/lib/nvidia
sudo mkdir /usr/lib/nvidia
sudo apt-get install --no-install-recommends nvidia-410
# Reboot. Check that GPUs are visible using the command: nvidia-smi

# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-10-0 \
    libcudnn7=7.4.1.5-1+cuda10.0  \
    libcudnn7-dev=7.4.1.5-1+cuda10.0

export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64 
PATH=${CUDA_HOME}/bin:${PATH} 
export PATH
```

- here is the output of `nvidia-smi` after restarting my machine:

```
Thu Aug 20 16:08:30 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K610M        On   | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P0    N/A /  N/A |    462MiB /   980MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I ran the example and I got this :

```
2020-08-20 16:21:43.407500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-20 16:21:43.443526: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.443804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro K610M computeCapability: 3.5
coreClock: 0.954GHz coreCount: 1 deviceMemorySize: 980.00MiB deviceMemoryBandwidth: 19.37GiB/s
2020-08-20 16:21:43.444047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 16:21:43.445279: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-20 16:21:43.446480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-20 16:21:43.446740: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-20 16:21:43.448068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-20 16:21:43.449061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-20 16:21:43.452192: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-20 16:21:43.452463: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.453175: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.453388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-20 16:21:43.453697: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-20 16:21:43.460640: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2793340000 Hz
2020-08-20 16:21:43.461051: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f3e6c000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-20 16:21:43.461065: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-20 16:21:43.495800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.496133: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557c1d871200 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-20 16:21:43.496147: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro K610M, Compute Capability 3.5
2020-08-20 16:21:43.496361: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.496607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro K610M computeCapability: 3.5
coreClock: 0.954GHz coreCount: 1 deviceMemorySize: 980.00MiB deviceMemoryBandwidth: 19.37GiB/s
2020-08-20 16:21:43.496663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 16:21:43.496680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-20 16:21:43.496693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-20 16:21:43.496708: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-20 16:21:43.496721: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-20 16:21:43.496735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-20 16:21:43.496748: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-20 16:21:43.496825: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.497100: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.497302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-20 16:21:43.497334: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-20 16:21:43.498181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-20 16:21:43.498192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-20 16:21:43.498197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-08-20 16:21:43.498320: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.498635: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-20 16:21:43.498921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 204 MB memory) -> physical GPU (device: 0, name: Quadro K610M, pci bus id: 0000:01:00.0, compute capability: 3.5)
```
and finally 

```
TensorFlow v2.2.0 ()
Python v3.6 (~/.local/share/r-miniconda/envs/r-reticulate/bin/python)
```
Many thanks.

**Comment by reyhanhgh** [comment]
Hi Sigrid and thanks for your response. No, it still does not work. 
Even by disabling GPU the training dies after 2-3 epochs. It gives me this warning also:

`2020-08-24 09:58:38.751594: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of free system memory.`

**Comment by skeydan** [comment]
You mean for your model or the website example? In any case, try experimenting with the batch size (successively lowering it) - at some point it should start to work ...

What does `free -m` say? This 

```
Allocation of  188160000 exceeds 10% of free system memory
```

(which should be in bytes) should imply that overall free memory would be at around 2G ...

**Comment by reyhanhgh** [comment]
Hi Sigrid. 
I managed to get it run finally for the Mnist example. but not still for my LSTM model that worked previously. 
Here is the output of `free -m`:
```
              total        used        free      shared  buff/cache   available
Mem:           7891        2539        3646         156        1705        4909
Swap:          1951           0        1951

```
