### ISSUE TITLE
R studio crashes when running cifar10_cnn example

### ISSUE THREAD

**Issue by coldfir3** [rstudio/keras#435]
When running the exact code found on https://tensorflow.rstudio.com/keras/articles/examples/cifar10_cnn.html

my R studio crashes with no error message. 
 
The screen on crashing is the following:
![image](https://user-images.githubusercontent.com/13731681/41501378-beb5a78c-7179-11e8-8b02-599c02743bae.png)

However, when i run the code found on
https://tensorflow.rstudio.com/keras/#mnist-example
the network is trained with no problems, it only complains about the CPU thing: "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2".

I am new to keras and tensorflow and have no idea how to debug this. Thanks for the help

After digging up i tracked the error to be related to convolutional networks, when i try to run a similar code on python i get the following error:

```
2018-06-16 16:35:09.416024: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:09.421090: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:09.423646: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:09.426395: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:09.428671: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:09.430831: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-06-16 16:35:10.616219: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:455] could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2018-06-16 16:35:10.618631: F T:\src\github\tensorflow\tensorflow\core\kernels\conv_ops.cc:713] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
```

**Comment by coldfir3** [comment]
I fixed the problem by updating my drivers, for some reason when i installed CUDA, the installer put some old drivers on my PC. After updating to the newest drivers and rebooting everything worked fine.

**Comment by stevedevney** [comment]
Exactly what drivers did you update?

**Comment by stevedevney** [comment]
ok, I'm running rstudio 1.1.453, with: my session as: 


`ersion 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.1.6    reticulate_1.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    lattice_0.20-35 zeallot_0.1.0   grid_3.5.1     
 [5] R6_2.2.2        jsonlite_1.5    magrittr_1.5    tfruns_1.3     
 [9] whisker_0.3-2   Matrix_1.2-14   tools_3.5.1     yaml_2.1.19    
[13] compiler_3.5.1  base64enc_0.1-3 tensorflow_1.8  knitr_1.20    `

I did as my question here: [Rstudio crashes when using fit_generator in keras](https://github.com/rstudio/keras/issues/466)

Thanks for the update.

**Comment by csitaula** [comment]
I am also facing same problem, although I have latest driver of CUDA. Any solution?
